// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveFeedVersion = `-- name: GetActiveFeedVersion :one
SELECT id, source_id, version_label, archive_sha256, activated_at
FROM catalog.feed_versions
WHERE source_id = $1 AND status = 'active'
`

type GetActiveFeedVersionRow struct {
	ID            int64              `json:"id"`
	SourceID      string             `json:"source_id"`
	VersionLabel  string             `json:"version_label"`
	ArchiveSha256 string             `json:"archive_sha256"`
	ActivatedAt   pgtype.Timestamptz `json:"activated_at"`
}

func (q *Queries) GetActiveFeedVersion(ctx context.Context, sourceID string) (GetActiveFeedVersionRow, error) {
	row := q.db.QueryRow(ctx, getActiveFeedVersion, sourceID)
	var i GetActiveFeedVersionRow
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.VersionLabel,
		&i.ArchiveSha256,
		&i.ActivatedAt,
	)
	return i, err
}

const getSourceHealth = `-- name: GetSourceHealth :one
SELECT source_id, last_attempt_at, last_success_at, last_failure_at, last_source_updated_at,
       last_valid_snapshot_at, consecutive_failures, last_error_code, entity_count, updated_at
FROM ops.source_health
WHERE source_id = $1
`

type GetSourceHealthRow struct {
	SourceID            string             `json:"source_id"`
	LastAttemptAt       pgtype.Timestamptz `json:"last_attempt_at"`
	LastSuccessAt       pgtype.Timestamptz `json:"last_success_at"`
	LastFailureAt       pgtype.Timestamptz `json:"last_failure_at"`
	LastSourceUpdatedAt pgtype.Timestamptz `json:"last_source_updated_at"`
	LastValidSnapshotAt pgtype.Timestamptz `json:"last_valid_snapshot_at"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	LastErrorCode       pgtype.Text        `json:"last_error_code"`
	EntityCount         pgtype.Int4        `json:"entity_count"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSourceHealth(ctx context.Context, sourceID string) (GetSourceHealthRow, error) {
	row := q.db.QueryRow(ctx, getSourceHealth, sourceID)
	var i GetSourceHealthRow
	err := row.Scan(
		&i.SourceID,
		&i.LastAttemptAt,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.LastSourceUpdatedAt,
		&i.LastValidSnapshotAt,
		&i.ConsecutiveFailures,
		&i.LastErrorCode,
		&i.EntityCount,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSourceHealthSuccess = `-- name: UpsertSourceHealthSuccess :exec
INSERT INTO ops.source_health (
  source_id, last_attempt_at, last_success_at, last_source_updated_at,
  last_valid_snapshot_at, consecutive_failures, last_error_code, last_error_safe_detail,
  entity_count, updated_at
) VALUES (
  $1, $2, $3,
  $4, $5, 0, NULL, NULL,
  $6, now()
)
ON CONFLICT (source_id) DO UPDATE SET
  last_attempt_at = EXCLUDED.last_attempt_at,
  last_success_at = EXCLUDED.last_success_at,
  last_source_updated_at = EXCLUDED.last_source_updated_at,
  last_valid_snapshot_at = EXCLUDED.last_valid_snapshot_at,
  consecutive_failures = 0,
  last_error_code = NULL,
  last_error_safe_detail = NULL,
  entity_count = EXCLUDED.entity_count,
  updated_at = now()
`

type UpsertSourceHealthSuccessParams struct {
	SourceID        string             `json:"source_id"`
	AttemptedAt     pgtype.Timestamptz `json:"attempted_at"`
	SucceededAt     pgtype.Timestamptz `json:"succeeded_at"`
	SourceUpdatedAt pgtype.Timestamptz `json:"source_updated_at"`
	SnapshotAt      pgtype.Timestamptz `json:"snapshot_at"`
	EntityCount     pgtype.Int4        `json:"entity_count"`
}

func (q *Queries) UpsertSourceHealthSuccess(ctx context.Context, arg UpsertSourceHealthSuccessParams) error {
	_, err := q.db.Exec(ctx, upsertSourceHealthSuccess,
		arg.SourceID,
		arg.AttemptedAt,
		arg.SucceededAt,
		arg.SourceUpdatedAt,
		arg.SnapshotAt,
		arg.EntityCount,
	)
	return err
}
