// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CatalogFeedVersionStatus string

const (
	CatalogFeedVersionStatusStaged     CatalogFeedVersionStatus = "staged"
	CatalogFeedVersionStatusActive     CatalogFeedVersionStatus = "active"
	CatalogFeedVersionStatusSuperseded CatalogFeedVersionStatus = "superseded"
	CatalogFeedVersionStatusFailed     CatalogFeedVersionStatus = "failed"
)

func (e *CatalogFeedVersionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CatalogFeedVersionStatus(s)
	case string:
		*e = CatalogFeedVersionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CatalogFeedVersionStatus: %T", src)
	}
	return nil
}

type NullCatalogFeedVersionStatus struct {
	CatalogFeedVersionStatus CatalogFeedVersionStatus `json:"catalog_feed_version_status"`
	Valid                    bool                     `json:"valid"` // Valid is true if CatalogFeedVersionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCatalogFeedVersionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CatalogFeedVersionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CatalogFeedVersionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCatalogFeedVersionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CatalogFeedVersionStatus), nil
}

type RealtimeFreshnessStatus string

const (
	RealtimeFreshnessStatusFresh   RealtimeFreshnessStatus = "fresh"
	RealtimeFreshnessStatusAging   RealtimeFreshnessStatus = "aging"
	RealtimeFreshnessStatusStale   RealtimeFreshnessStatus = "stale"
	RealtimeFreshnessStatusUnknown RealtimeFreshnessStatus = "unknown"
)

func (e *RealtimeFreshnessStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RealtimeFreshnessStatus(s)
	case string:
		*e = RealtimeFreshnessStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RealtimeFreshnessStatus: %T", src)
	}
	return nil
}

type NullRealtimeFreshnessStatus struct {
	RealtimeFreshnessStatus RealtimeFreshnessStatus `json:"realtime_freshness_status"`
	Valid                   bool                    `json:"valid"` // Valid is true if RealtimeFreshnessStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRealtimeFreshnessStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RealtimeFreshnessStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RealtimeFreshnessStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRealtimeFreshnessStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RealtimeFreshnessStatus), nil
}

type TransitMode string

const (
	TransitModeBus          TransitMode = "bus"
	TransitModeLightRail    TransitMode = "light_rail"
	TransitModeStreetcar    TransitMode = "streetcar"
	TransitModeCommuterRail TransitMode = "commuter_rail"
	TransitModeFerry        TransitMode = "ferry"
	TransitModeOther        TransitMode = "other"
	TransitModeUnknown      TransitMode = "unknown"
)

func (e *TransitMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransitMode(s)
	case string:
		*e = TransitMode(s)
	default:
		return fmt.Errorf("unsupported scan type for TransitMode: %T", src)
	}
	return nil
}

type NullTransitMode struct {
	TransitMode TransitMode `json:"transit_mode"`
	Valid       bool        `json:"valid"` // Valid is true if TransitMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransitMode) Scan(value interface{}) error {
	if value == nil {
		ns.TransitMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransitMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransitMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransitMode), nil
}

type CatalogFeedVersion struct {
	ID                int64                    `json:"id"`
	SourceID          string                   `json:"source_id"`
	VersionLabel      string                   `json:"version_label"`
	ArchiveSha256     string                   `json:"archive_sha256"`
	SourcePublishedAt pgtype.Timestamptz       `json:"source_published_at"`
	FetchedAt         pgtype.Timestamptz       `json:"fetched_at"`
	ActivatedAt       pgtype.Timestamptz       `json:"activated_at"`
	Status            CatalogFeedVersionStatus `json:"status"`
	ImportReport      []byte                   `json:"import_report"`
	CreatedAt         pgtype.Timestamptz       `json:"created_at"`
}

type CatalogImportRun struct {
	ID            int64              `json:"id"`
	SourceID      string             `json:"source_id"`
	FeedVersionID pgtype.Int8        `json:"feed_version_id"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	Outcome       string             `json:"outcome"`
	Report        []byte             `json:"report"`
	FailureCode   pgtype.Text        `json:"failure_code"`
}

type CatalogSource struct {
	ID                string             `json:"id"`
	DisplayName       string             `json:"display_name"`
	ProviderName      string             `json:"provider_name"`
	SourceKind        string             `json:"source_kind"`
	AgencyID          pgtype.Text        `json:"agency_id"`
	BaseUrl           pgtype.Text        `json:"base_url"`
	CadenceSeconds    pgtype.Int4        `json:"cadence_seconds"`
	FreshAfterSeconds pgtype.Int4        `json:"fresh_after_seconds"`
	StaleAfterSeconds pgtype.Int4        `json:"stale_after_seconds"`
	Attribution       pgtype.Text        `json:"attribution"`
	TermsUrl          pgtype.Text        `json:"terms_url"`
	Enabled           bool               `json:"enabled"`
	AdapterVersion    string             `json:"adapter_version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type OpsSourceHealth struct {
	SourceID            string             `json:"source_id"`
	LastAttemptAt       pgtype.Timestamptz `json:"last_attempt_at"`
	LastSuccessAt       pgtype.Timestamptz `json:"last_success_at"`
	LastFailureAt       pgtype.Timestamptz `json:"last_failure_at"`
	LastSourceUpdatedAt pgtype.Timestamptz `json:"last_source_updated_at"`
	LastValidSnapshotAt pgtype.Timestamptz `json:"last_valid_snapshot_at"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	LastErrorCode       pgtype.Text        `json:"last_error_code"`
	LastErrorSafeDetail pgtype.Text        `json:"last_error_safe_detail"`
	EntityCount         pgtype.Int4        `json:"entity_count"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type RealtimeSnapshot struct {
	ID               int64              `json:"id"`
	SourceID         string             `json:"source_id"`
	FeedVersionID    pgtype.Int8        `json:"feed_version_id"`
	SourceUpdatedAt  pgtype.Timestamptz `json:"source_updated_at"`
	FetchedAt        pgtype.Timestamptz `json:"fetched_at"`
	ProcessedAt      pgtype.Timestamptz `json:"processed_at"`
	EntityCount      int32              `json:"entity_count"`
	ContentSha256    string             `json:"content_sha256"`
	IsValid          bool               `json:"is_valid"`
	ValidationReport []byte             `json:"validation_report"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type RealtimeVehicleCurrent struct {
	SourceID                 string                  `json:"source_id"`
	PublicID                 string                  `json:"public_id"`
	SourceVehicleID          string                  `json:"source_vehicle_id"`
	SnapshotID               int64                   `json:"snapshot_id"`
	FeedVersionID            pgtype.Int8             `json:"feed_version_id"`
	RoutePublicID            pgtype.Text             `json:"route_public_id"`
	TripPublicID             pgtype.Text             `json:"trip_public_id"`
	BlockID                  pgtype.Text             `json:"block_id"`
	Mode                     TransitMode             `json:"mode"`
	DirectionID              pgtype.Int2             `json:"direction_id"`
	Headsign                 pgtype.Text             `json:"headsign"`
	Point                    string                  `json:"point"`
	Bearing                  pgtype.Numeric          `json:"bearing"`
	SpeedMetersPerSecond     pgtype.Numeric          `json:"speed_meters_per_second"`
	CurrentStopPublicID      pgtype.Text             `json:"current_stop_public_id"`
	NextStopPublicID         pgtype.Text             `json:"next_stop_public_id"`
	ScheduleDeviationSeconds pgtype.Int4             `json:"schedule_deviation_seconds"`
	InService                bool                    `json:"in_service"`
	SourceUpdatedAt          pgtype.Timestamptz      `json:"source_updated_at"`
	EntityUpdatedAt          pgtype.Timestamptz      `json:"entity_updated_at"`
	FetchedAt                pgtype.Timestamptz      `json:"fetched_at"`
	ProcessedAt              pgtype.Timestamptz      `json:"processed_at"`
	ExpiresAt                pgtype.Timestamptz      `json:"expires_at"`
	FreshnessStatus          RealtimeFreshnessStatus `json:"freshness_status"`
	UpdatedAt                pgtype.Timestamptz      `json:"updated_at"`
}

type TransitRoute struct {
	FeedVersionID int64              `json:"feed_version_id"`
	PublicID      string             `json:"public_id"`
	SourceRouteID string             `json:"source_route_id"`
	ShortName     pgtype.Text        `json:"short_name"`
	LongName      pgtype.Text        `json:"long_name"`
	Description   pgtype.Text        `json:"description"`
	Mode          TransitMode        `json:"mode"`
	Color         pgtype.Text        `json:"color"`
	TextColor     pgtype.Text        `json:"text_color"`
	SortOrder     pgtype.Int4        `json:"sort_order"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type TransitShape struct {
	FeedVersionID int64              `json:"feed_version_id"`
	PublicID      string             `json:"public_id"`
	SourceShapeID string             `json:"source_shape_id"`
	Line          interface{}        `json:"line"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type TransitStop struct {
	FeedVersionID      int64              `json:"feed_version_id"`
	PublicID           string             `json:"public_id"`
	SourceStopID       string             `json:"source_stop_id"`
	Name               string             `json:"name"`
	Code               pgtype.Text        `json:"code"`
	ParentPublicID     pgtype.Text        `json:"parent_public_id"`
	PlatformCode       pgtype.Text        `json:"platform_code"`
	Mode               TransitMode        `json:"mode"`
	WheelchairBoarding int16              `json:"wheelchair_boarding"`
	Point              string             `json:"point"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type TransitStopTime struct {
	FeedVersionID    int64       `json:"feed_version_id"`
	TripPublicID     string      `json:"trip_public_id"`
	StopPublicID     string      `json:"stop_public_id"`
	StopSequence     int32       `json:"stop_sequence"`
	ArrivalSeconds   pgtype.Int4 `json:"arrival_seconds"`
	DepartureSeconds pgtype.Int4 `json:"departure_seconds"`
	PickupType       int16       `json:"pickup_type"`
	DropOffType      int16       `json:"drop_off_type"`
	Timepoint        pgtype.Bool `json:"timepoint"`
}

type TransitTrip struct {
	FeedVersionID        int64              `json:"feed_version_id"`
	PublicID             string             `json:"public_id"`
	SourceTripID         string             `json:"source_trip_id"`
	RoutePublicID        string             `json:"route_public_id"`
	ServiceID            string             `json:"service_id"`
	Headsign             pgtype.Text        `json:"headsign"`
	DirectionID          pgtype.Int2        `json:"direction_id"`
	BlockID              pgtype.Text        `json:"block_id"`
	ShapePublicID        pgtype.Text        `json:"shape_public_id"`
	WheelchairAccessible int16              `json:"wheelchair_accessible"`
	BikesAllowed         int16              `json:"bikes_allowed"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}
