// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nearby_stops.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listNearbyStopsPerMode = `-- name: ListNearbyStopsPerMode :many
WITH input AS (
  SELECT ST_SetSRID(ST_MakePoint($3::double precision, $4::double precision), 4326)::geography AS point
), nearby AS (
  SELECT s.public_id, s.name, s.mode, s.point,
         ST_Distance(s.point, input.point)::double precision AS distance_meters,
         row_number() OVER (PARTITION BY s.mode ORDER BY s.point <-> input.point, s.public_id) AS mode_rank
  FROM transit.stops AS s
  JOIN catalog.feed_versions f ON f.id = s.feed_version_id AND f.status = 'active'
  CROSS JOIN input
  WHERE ST_DWithin(s.point, input.point, $5::double precision)
    AND (cardinality($6::text[]) IS NULL OR s.mode::text = ANY($6::text[]))
    AND ($7::boolean IS NULL
      OR ($7::boolean = true AND s.wheelchair_boarding = 1)
      OR ($7::boolean = false AND s.wheelchair_boarding <> 1))
)
SELECT public_id, name, mode, ST_X(point::geometry) AS longitude, ST_Y(point::geometry) AS latitude, distance_meters
FROM nearby
WHERE mode_rank <= $1::bigint
ORDER BY distance_meters, public_id
LIMIT $2::integer
`

type ListNearbyStopsPerModeParams struct {
	LimitPerMode         int64       `json:"limit_per_mode"`
	TotalLimit           int32       `json:"total_limit"`
	Lon                  float64     `json:"lon"`
	Lat                  float64     `json:"lat"`
	RadiusMeters         float64     `json:"radius_meters"`
	Modes                []string    `json:"modes"`
	WheelchairAccessible pgtype.Bool `json:"wheelchair_accessible"`
}

type ListNearbyStopsPerModeRow struct {
	PublicID       string      `json:"public_id"`
	Name           string      `json:"name"`
	Mode           TransitMode `json:"mode"`
	Longitude      interface{} `json:"longitude"`
	Latitude       interface{} `json:"latitude"`
	DistanceMeters float64     `json:"distance_meters"`
}

func (q *Queries) ListNearbyStopsPerMode(ctx context.Context, arg ListNearbyStopsPerModeParams) ([]ListNearbyStopsPerModeRow, error) {
	rows, err := q.db.Query(ctx, listNearbyStopsPerMode,
		arg.LimitPerMode,
		arg.TotalLimit,
		arg.Lon,
		arg.Lat,
		arg.RadiusMeters,
		arg.Modes,
		arg.WheelchairAccessible,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNearbyStopsPerModeRow{}
	for rows.Next() {
		var i ListNearbyStopsPerModeRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Name,
			&i.Mode,
			&i.Longitude,
			&i.Latitude,
			&i.DistanceMeters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
