// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNotificationDeliveries = `-- name: ClaimNotificationDeliveries :many
WITH candidates AS (
  SELECT d.id
  FROM app.notification_deliveries d
  JOIN app.push_tokens token ON token.id = d.push_token_id
  JOIN app.subscriptions subscription ON subscription.id = d.subscription_id
  WHERE d.expires_at > $1
    AND subscription.expires_at > $1
    AND subscription.deleted_at IS NULL
    AND token.disabled_at IS NULL
    AND d.attempts < $2::smallint
    AND (
      (d.status IN ('pending', 'retry_pending') AND (d.next_attempt_at IS NULL OR d.next_attempt_at <= $1))
      OR (d.status = 'sending' AND d.claim_until <= $1)
    )
  ORDER BY d.expires_at, d.created_at, d.id
  FOR UPDATE OF d SKIP LOCKED
  LIMIT $3::integer
), claimed AS (
  UPDATE app.notification_deliveries d
  SET status = 'sending', attempts = d.attempts + 1,
      claim_until = $4, claim_token = $5,
      updated_at = $1
  FROM candidates c
  WHERE d.id = c.id
  RETURNING d.id, d.subscription_id, d.push_token_id, d.notification_type,
            d.payload, d.expires_at, d.attempts, d.claim_token, d.dedupe_key
)
SELECT claimed.id, claimed.subscription_id, claimed.push_token_id,
       claimed.notification_type, claimed.payload, claimed.expires_at,
       claimed.attempts, claimed.claim_token, claimed.dedupe_key,
       token.token_ciphertext, token.encryption_key_id,
       subscription.quiet_start, subscription.quiet_end, subscription.quiet_time_zone
FROM claimed
JOIN app.push_tokens token ON token.id = claimed.push_token_id
JOIN app.subscriptions subscription ON subscription.id = claimed.subscription_id
ORDER BY claimed.expires_at, claimed.id
`

type ClaimNotificationDeliveriesParams struct {
	NowAt       pgtype.Timestamptz `json:"now_at"`
	MaxAttempts int16              `json:"max_attempts"`
	RowLimit    int32              `json:"row_limit"`
	ClaimUntil  pgtype.Timestamptz `json:"claim_until"`
	ClaimToken  pgtype.UUID        `json:"claim_token"`
}

type ClaimNotificationDeliveriesRow struct {
	ID               pgtype.UUID        `json:"id"`
	SubscriptionID   pgtype.UUID        `json:"subscription_id"`
	PushTokenID      pgtype.UUID        `json:"push_token_id"`
	NotificationType string             `json:"notification_type"`
	Payload          []byte             `json:"payload"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	Attempts         int16              `json:"attempts"`
	ClaimToken       pgtype.UUID        `json:"claim_token"`
	DedupeKey        string             `json:"dedupe_key"`
	TokenCiphertext  []byte             `json:"token_ciphertext"`
	EncryptionKeyID  string             `json:"encryption_key_id"`
	QuietStart       pgtype.Time        `json:"quiet_start"`
	QuietEnd         pgtype.Time        `json:"quiet_end"`
	QuietTimeZone    pgtype.Text        `json:"quiet_time_zone"`
}

// Claiming is a single transaction statement. SKIP LOCKED permits independent
// workers without duplicate sends; claim_until recovers a crashed worker while
// the expiry predicate prevents a late time-sensitive retry.
func (q *Queries) ClaimNotificationDeliveries(ctx context.Context, arg ClaimNotificationDeliveriesParams) ([]ClaimNotificationDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, claimNotificationDeliveries,
		arg.NowAt,
		arg.MaxAttempts,
		arg.RowLimit,
		arg.ClaimUntil,
		arg.ClaimToken,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimNotificationDeliveriesRow{}
	for rows.Next() {
		var i ClaimNotificationDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.PushTokenID,
			&i.NotificationType,
			&i.Payload,
			&i.ExpiresAt,
			&i.Attempts,
			&i.ClaimToken,
			&i.DedupeKey,
			&i.TokenCiphertext,
			&i.EncryptionKeyID,
			&i.QuietStart,
			&i.QuietEnd,
			&i.QuietTimeZone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const disablePushToken = `-- name: DisablePushToken :exec
UPDATE app.push_tokens
SET disabled_at = $1, disabled_reason = $2, updated_at = $1
WHERE id = $3 AND disabled_at IS NULL
`

type DisablePushTokenParams struct {
	DisabledAt     pgtype.Timestamptz `json:"disabled_at"`
	DisabledReason pgtype.Text        `json:"disabled_reason"`
	ID             pgtype.UUID        `json:"id"`
}

func (q *Queries) DisablePushToken(ctx context.Context, arg DisablePushTokenParams) error {
	_, err := q.db.Exec(ctx, disablePushToken, arg.DisabledAt, arg.DisabledReason, arg.ID)
	return err
}

const disableTokenForInvalidReceipt = `-- name: DisableTokenForInvalidReceipt :execrows
UPDATE app.push_tokens token
SET disabled_at = $1, disabled_reason = 'invalid_token',
    updated_at = $1
FROM app.notification_deliveries delivery
WHERE delivery.provider_ticket_id = $2
  AND delivery.push_token_id = token.id
  AND token.disabled_at IS NULL
`

type DisableTokenForInvalidReceiptParams struct {
	DisabledAt       pgtype.Timestamptz `json:"disabled_at"`
	ProviderTicketID pgtype.Text        `json:"provider_ticket_id"`
}

// The ticket predicate ensures an arbitrary receipt cannot disable a token.
func (q *Queries) DisableTokenForInvalidReceipt(ctx context.Context, arg DisableTokenForInvalidReceiptParams) (int64, error) {
	result, err := q.db.Exec(ctx, disableTokenForInvalidReceipt, arg.DisabledAt, arg.ProviderTicketID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expirePendingDeliveries = `-- name: ExpirePendingDeliveries :execrows
UPDATE app.notification_deliveries
SET status = 'expired', claim_until = NULL, claim_token = NULL,
    next_attempt_at = NULL, updated_at = $1
WHERE status IN ('pending', 'retry_pending', 'sending')
  AND expires_at <= $1
`

// Expired notifications are terminal. They must never be retried after a
// worker outage or a quiet-hours deferral.
func (q *Queries) ExpirePendingDeliveries(ctx context.Context, nowAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, expirePendingDeliveries, nowAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertNotificationDelivery = `-- name: InsertNotificationDelivery :one
INSERT INTO app.notification_deliveries (
  id, subscription_id, push_token_id, notification_type, dedupe_key, payload,
  occurred_at, expires_at, status, next_attempt_at
) VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7, $8, 'pending', $9
)
ON CONFLICT (dedupe_key) DO UPDATE
SET dedupe_key = EXCLUDED.dedupe_key
RETURNING id
`

type InsertNotificationDeliveryParams struct {
	ID               pgtype.UUID        `json:"id"`
	SubscriptionID   pgtype.UUID        `json:"subscription_id"`
	PushTokenID      pgtype.UUID        `json:"push_token_id"`
	NotificationType string             `json:"notification_type"`
	DedupeKey        string             `json:"dedupe_key"`
	Payload          []byte             `json:"payload"`
	OccurredAt       pgtype.Timestamptz `json:"occurred_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	NextAttemptAt    pgtype.Timestamptz `json:"next_attempt_at"`
}

// The unique dedupe_key is the concurrency boundary: concurrent workers may
// attempt the same event, but only one delivery is materialized.
// A duplicate is an expected outcome of concurrent event evaluation. Return
// the already-materialized delivery instead of making callers handle it as a
// missing row.
func (q *Queries) InsertNotificationDelivery(ctx context.Context, arg InsertNotificationDeliveryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertNotificationDelivery,
		arg.ID,
		arg.SubscriptionID,
		arg.PushTokenID,
		arg.NotificationType,
		arg.DedupeKey,
		arg.Payload,
		arg.OccurredAt,
		arg.ExpiresAt,
		arg.NextAttemptAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const markNotificationDeliveryExpired = `-- name: MarkNotificationDeliveryExpired :execrows
UPDATE app.notification_deliveries
SET status = 'expired', claim_until = NULL, claim_token = NULL, next_attempt_at = NULL,
    updated_at = $1
WHERE id = $2 AND status = 'sending'
  AND claim_token = $3
`

type MarkNotificationDeliveryExpiredParams struct {
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ID         pgtype.UUID        `json:"id"`
	ClaimToken pgtype.UUID        `json:"claim_token"`
}

func (q *Queries) MarkNotificationDeliveryExpired(ctx context.Context, arg MarkNotificationDeliveryExpiredParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationDeliveryExpired, arg.UpdatedAt, arg.ID, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationDeliveryFailed = `-- name: MarkNotificationDeliveryFailed :execrows
UPDATE app.notification_deliveries
SET status = 'failed', claim_until = NULL, claim_token = NULL, next_attempt_at = NULL,
    last_error_code = $1, updated_at = $2
WHERE id = $3 AND status = 'sending'
  AND claim_token = $4
`

type MarkNotificationDeliveryFailedParams struct {
	ErrorCode  pgtype.Text        `json:"error_code"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ID         pgtype.UUID        `json:"id"`
	ClaimToken pgtype.UUID        `json:"claim_token"`
}

func (q *Queries) MarkNotificationDeliveryFailed(ctx context.Context, arg MarkNotificationDeliveryFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationDeliveryFailed,
		arg.ErrorCode,
		arg.UpdatedAt,
		arg.ID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationDeliveryRetry = `-- name: MarkNotificationDeliveryRetry :execrows
UPDATE app.notification_deliveries
SET status = 'retry_pending', next_attempt_at = $1,
    claim_until = NULL, claim_token = NULL, last_error_code = $2,
    updated_at = $3
WHERE id = $4 AND status = 'sending'
  AND claim_token = $5
`

type MarkNotificationDeliveryRetryParams struct {
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	ErrorCode     pgtype.Text        `json:"error_code"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ID            pgtype.UUID        `json:"id"`
	ClaimToken    pgtype.UUID        `json:"claim_token"`
}

func (q *Queries) MarkNotificationDeliveryRetry(ctx context.Context, arg MarkNotificationDeliveryRetryParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationDeliveryRetry,
		arg.NextAttemptAt,
		arg.ErrorCode,
		arg.UpdatedAt,
		arg.ID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationDeliverySent = `-- name: MarkNotificationDeliverySent :execrows
UPDATE app.notification_deliveries
SET status = 'sent', provider_ticket_id = $1,
    sent_at = $2, claim_until = NULL, claim_token = NULL,
    next_attempt_at = NULL,
    last_error_code = NULL, updated_at = $2
WHERE id = $3 AND status = 'sending'
  AND claim_token = $4
`

type MarkNotificationDeliverySentParams struct {
	ProviderTicketID pgtype.Text        `json:"provider_ticket_id"`
	SentAt           pgtype.Timestamptz `json:"sent_at"`
	ID               pgtype.UUID        `json:"id"`
	ClaimToken       pgtype.UUID        `json:"claim_token"`
}

// A delivery can only become sent while held by a worker. This prevents a
// late worker from overwriting a recovered lease or a terminal transition.
func (q *Queries) MarkNotificationDeliverySent(ctx context.Context, arg MarkNotificationDeliverySentParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationDeliverySent,
		arg.ProviderTicketID,
		arg.SentAt,
		arg.ID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordNotificationReceipt = `-- name: RecordNotificationReceipt :one
INSERT INTO app.notification_receipts (
  provider_ticket_id, received_at, status, error_code, safe_detail, processed_at
) VALUES (
  $1, $2, $3,
  $4, $5, $6
)
ON CONFLICT (provider_ticket_id) DO UPDATE
SET received_at = EXCLUDED.received_at, status = EXCLUDED.status,
    error_code = EXCLUDED.error_code, safe_detail = EXCLUDED.safe_detail,
    processed_at = EXCLUDED.processed_at
RETURNING provider_ticket_id
`

type RecordNotificationReceiptParams struct {
	ProviderTicketID string             `json:"provider_ticket_id"`
	ReceivedAt       pgtype.Timestamptz `json:"received_at"`
	Status           string             `json:"status"`
	ErrorCode        pgtype.Text        `json:"error_code"`
	SafeDetail       pgtype.Text        `json:"safe_detail"`
	ProcessedAt      pgtype.Timestamptz `json:"processed_at"`
}

// A provider receipt is tied to the ticket created by a successful send. The
// receipt body is constrained by the application before it reaches this query.
func (q *Queries) RecordNotificationReceipt(ctx context.Context, arg RecordNotificationReceiptParams) (string, error) {
	row := q.db.QueryRow(ctx, recordNotificationReceipt,
		arg.ProviderTicketID,
		arg.ReceivedAt,
		arg.Status,
		arg.ErrorCode,
		arg.SafeDetail,
		arg.ProcessedAt,
	)
	var provider_ticket_id string
	err := row.Scan(&provider_ticket_id)
	return provider_ticket_id, err
}
