// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNotificationDeliveries = `-- name: ClaimNotificationDeliveries :many
WITH candidates AS (
  SELECT d.id
  FROM app.notification_deliveries d
  JOIN app.push_tokens token ON token.id = d.push_token_id
  JOIN app.subscriptions subscription ON subscription.id = d.subscription_id
  WHERE d.expires_at > $1
    AND subscription.expires_at > $1
    AND subscription.deleted_at IS NULL
    AND token.disabled_at IS NULL
    AND d.attempts < $2::smallint
    AND (
      (d.status IN ('pending', 'retry_pending') AND (d.next_attempt_at IS NULL OR d.next_attempt_at <= $1))
      OR (d.status = 'sending' AND d.claim_until <= $1)
    )
  ORDER BY d.expires_at, d.created_at, d.id
  FOR UPDATE OF d SKIP LOCKED
  LIMIT $3::integer
), claimed AS (
  UPDATE app.notification_deliveries d
  SET status = 'sending', attempts = d.attempts + 1,
      claim_until = $4, updated_at = $1
  FROM candidates c
  WHERE d.id = c.id
  RETURNING d.id, d.subscription_id, d.push_token_id, d.notification_type,
            d.payload, d.expires_at, d.attempts
)
SELECT claimed.id, claimed.subscription_id, claimed.push_token_id,
       claimed.notification_type, claimed.payload, claimed.expires_at,
       claimed.attempts, token.token_ciphertext, token.encryption_key_id,
       subscription.quiet_start, subscription.quiet_end, subscription.quiet_time_zone
FROM claimed
JOIN app.push_tokens token ON token.id = claimed.push_token_id
JOIN app.subscriptions subscription ON subscription.id = claimed.subscription_id
ORDER BY claimed.expires_at, claimed.id
`

type ClaimNotificationDeliveriesParams struct {
	NowAt       pgtype.Timestamptz `json:"now_at"`
	MaxAttempts int16              `json:"max_attempts"`
	RowLimit    int32              `json:"row_limit"`
	ClaimUntil  pgtype.Timestamptz `json:"claim_until"`
}

type ClaimNotificationDeliveriesRow struct {
	ID               pgtype.UUID        `json:"id"`
	SubscriptionID   pgtype.UUID        `json:"subscription_id"`
	PushTokenID      pgtype.UUID        `json:"push_token_id"`
	NotificationType string             `json:"notification_type"`
	Payload          []byte             `json:"payload"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	Attempts         int16              `json:"attempts"`
	TokenCiphertext  []byte             `json:"token_ciphertext"`
	EncryptionKeyID  string             `json:"encryption_key_id"`
	QuietStart       pgtype.Time        `json:"quiet_start"`
	QuietEnd         pgtype.Time        `json:"quiet_end"`
	QuietTimeZone    pgtype.Text        `json:"quiet_time_zone"`
}

// Claiming is a single transaction statement. SKIP LOCKED permits independent
// workers without duplicate sends; claim_until recovers a crashed worker while
// the expiry predicate prevents a late time-sensitive retry.
func (q *Queries) ClaimNotificationDeliveries(ctx context.Context, arg ClaimNotificationDeliveriesParams) ([]ClaimNotificationDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, claimNotificationDeliveries,
		arg.NowAt,
		arg.MaxAttempts,
		arg.RowLimit,
		arg.ClaimUntil,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimNotificationDeliveriesRow{}
	for rows.Next() {
		var i ClaimNotificationDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.PushTokenID,
			&i.NotificationType,
			&i.Payload,
			&i.ExpiresAt,
			&i.Attempts,
			&i.TokenCiphertext,
			&i.EncryptionKeyID,
			&i.QuietStart,
			&i.QuietEnd,
			&i.QuietTimeZone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const disablePushToken = `-- name: DisablePushToken :exec
UPDATE app.push_tokens
SET disabled_at = $1, disabled_reason = $2, updated_at = $1
WHERE id = $3 AND disabled_at IS NULL
`

type DisablePushTokenParams struct {
	DisabledAt     pgtype.Timestamptz `json:"disabled_at"`
	DisabledReason pgtype.Text        `json:"disabled_reason"`
	ID             pgtype.UUID        `json:"id"`
}

func (q *Queries) DisablePushToken(ctx context.Context, arg DisablePushTokenParams) error {
	_, err := q.db.Exec(ctx, disablePushToken, arg.DisabledAt, arg.DisabledReason, arg.ID)
	return err
}

const expirePendingDeliveries = `-- name: ExpirePendingDeliveries :execrows
UPDATE app.notification_deliveries
SET status = 'expired', next_attempt_at = NULL, updated_at = $1
WHERE status IN ('pending', 'retry_pending', 'sending')
  AND expires_at <= $1
`

// Expired notifications are terminal. They must never be retried after a
// worker outage or a quiet-hours deferral.
func (q *Queries) ExpirePendingDeliveries(ctx context.Context, nowAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, expirePendingDeliveries, nowAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertNotificationDelivery = `-- name: InsertNotificationDelivery :one
INSERT INTO app.notification_deliveries (
  id, subscription_id, push_token_id, notification_type, dedupe_key, payload,
  occurred_at, expires_at, status, next_attempt_at
) VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7, $8, 'pending', $9
)
ON CONFLICT (dedupe_key) DO NOTHING
RETURNING id
`

type InsertNotificationDeliveryParams struct {
	ID               pgtype.UUID        `json:"id"`
	SubscriptionID   pgtype.UUID        `json:"subscription_id"`
	PushTokenID      pgtype.UUID        `json:"push_token_id"`
	NotificationType string             `json:"notification_type"`
	DedupeKey        string             `json:"dedupe_key"`
	Payload          []byte             `json:"payload"`
	OccurredAt       pgtype.Timestamptz `json:"occurred_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	NextAttemptAt    pgtype.Timestamptz `json:"next_attempt_at"`
}

// The unique dedupe_key is the concurrency boundary: concurrent workers may
// attempt the same event, but only one delivery is materialized.
func (q *Queries) InsertNotificationDelivery(ctx context.Context, arg InsertNotificationDeliveryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertNotificationDelivery,
		arg.ID,
		arg.SubscriptionID,
		arg.PushTokenID,
		arg.NotificationType,
		arg.DedupeKey,
		arg.Payload,
		arg.OccurredAt,
		arg.ExpiresAt,
		arg.NextAttemptAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
