// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	GetActiveFeedVersion(ctx context.Context, sourceID string) (GetActiveFeedVersionRow, error)
	GetSourceHealth(ctx context.Context, sourceID string) (GetSourceHealthRow, error)
	ListCurrentVehicles(ctx context.Context, sourceIds []string) ([]ListCurrentVehiclesRow, error)
	ListNearbyStopsPerMode(ctx context.Context, arg ListNearbyStopsPerModeParams) ([]ListNearbyStopsPerModeRow, error)
	UpsertSourceHealthSuccess(ctx context.Context, arg UpsertSourceHealthSuccessParams) error
}

var _ Querier = (*Queries)(nil)
