// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Claiming is a single transaction statement. SKIP LOCKED permits independent
	// workers without duplicate sends; claim_until recovers a crashed worker while
	// the expiry predicate prevents a late time-sensitive retry.
	ClaimNotificationDeliveries(ctx context.Context, arg ClaimNotificationDeliveriesParams) ([]ClaimNotificationDeliveriesRow, error)
	DisablePushToken(ctx context.Context, arg DisablePushTokenParams) error
	// The ticket predicate ensures an arbitrary receipt cannot disable a token.
	DisableTokenForInvalidReceipt(ctx context.Context, arg DisableTokenForInvalidReceiptParams) (int64, error)
	// Expired notifications are terminal. They must never be retried after a
	// worker outage or a quiet-hours deferral.
	ExpirePendingDeliveries(ctx context.Context, nowAt pgtype.Timestamptz) (int64, error)
	GetActiveFeedVersion(ctx context.Context, sourceID string) (GetActiveFeedVersionRow, error)
	GetCatalogRoute(ctx context.Context, publicID string) (GetCatalogRouteRow, error)
	GetCatalogStop(ctx context.Context, publicID string) (GetCatalogStopRow, error)
	GetCurrentAlert(ctx context.Context, arg GetCurrentAlertParams) (GetCurrentAlertRow, error)
	GetSourceHealth(ctx context.Context, sourceID string) (GetSourceHealthRow, error)
	// Readiness deliberately requires a valid snapshot and its corresponding
	// successful source-health record. A database connection alone is not enough
	// to describe stale or absent transit data as ready.
	HasReadyVehicleData(ctx context.Context) (bool, error)
	// The unique dedupe_key is the concurrency boundary: concurrent workers may
	// attempt the same event, but only one delivery is materialized.
	// A duplicate is an expected outcome of concurrent event evaluation. Return
	// the already-materialized delivery instead of making callers handle it as a
	// missing row.
	InsertNotificationDelivery(ctx context.Context, arg InsertNotificationDeliveryParams) (pgtype.UUID, error)
	// The public static endpoints currently combine enabled active feeds. The
	// newest activation is the response version marker until the API exposes a
	// multi-source static manifest.
	LatestActiveFeedVersionLabel(ctx context.Context) (string, error)
	ListCurrentAlerts(ctx context.Context, arg ListCurrentAlertsParams) ([]ListCurrentAlertsRow, error)
	ListCurrentVehicles(ctx context.Context, sourceIds []string) ([]ListCurrentVehiclesRow, error)
	ListNearbyStopsPerMode(ctx context.Context, arg ListNearbyStopsPerModeParams) ([]ListNearbyStopsPerModeRow, error)
	ListRouteDirections(ctx context.Context, routePublicID string) ([]ListRouteDirectionsRow, error)
	ListRouteShapes(ctx context.Context, arg ListRouteShapesParams) ([]ListRouteShapesRow, error)
	ListRouteStops(ctx context.Context, arg ListRouteStopsParams) ([]ListRouteStopsRow, error)
	ListRoutes(ctx context.Context, arg ListRoutesParams) ([]ListRoutesRow, error)
	// Current updates are optional enrichment. Static times are still returned
	// when no matching valid realtime entity exists.
	ListStopArrivalCandidates(ctx context.Context, arg ListStopArrivalCandidatesParams) ([]ListStopArrivalCandidatesRow, error)
	// Calendar exceptions take precedence over weekday service. Service-day seconds
	// are deliberately returned unchanged so after-midnight trips remain correct.
	ListStopSchedule(ctx context.Context, arg ListStopScheduleParams) ([]ListStopScheduleRow, error)
	ListStops(ctx context.Context, arg ListStopsParams) ([]ListStopsRow, error)
	// Observations are normalized positions, not a claim about schedule adherence.
	// A caller-enforced 30 day window keeps this read aligned with retention.
	ListVehicleHistory(ctx context.Context, arg ListVehicleHistoryParams) ([]ListVehicleHistoryRow, error)
	MarkNotificationDeliveryExpired(ctx context.Context, arg MarkNotificationDeliveryExpiredParams) (int64, error)
	MarkNotificationDeliveryFailed(ctx context.Context, arg MarkNotificationDeliveryFailedParams) (int64, error)
	MarkNotificationDeliveryRetry(ctx context.Context, arg MarkNotificationDeliveryRetryParams) (int64, error)
	// A delivery can only become sent while held by a worker. This prevents a
	// late worker from overwriting a recovered lease or a terminal transition.
	MarkNotificationDeliverySent(ctx context.Context, arg MarkNotificationDeliverySentParams) (int64, error)
	// A provider receipt is tied to the ticket created by a successful send. The
	// receipt body is constrained by the application before it reaches this query.
	RecordNotificationReceipt(ctx context.Context, arg RecordNotificationReceiptParams) (string, error)
	StopFeedTimezone(ctx context.Context, stopID string) (pgtype.Text, error)
	UpsertSourceHealthSuccess(ctx context.Context, arg UpsertSourceHealthSuccessParams) error
}

var _ Querier = (*Queries)(nil)
