// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: realtime.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentAlert = `-- name: GetCurrentAlert :one
SELECT source_id, entity_id, cause, effect, COALESCE(header_text,'') AS header_text,
       COALESCE(description_text,'') AS description_text, COALESCE(url,'') AS url,
       active_from, active_until, fetched_at, processed_at
FROM realtime.alerts_current
WHERE source_id=$1 AND entity_id=$2
`

type GetCurrentAlertParams struct {
	SourceID string `json:"source_id"`
	EntityID string `json:"entity_id"`
}

type GetCurrentAlertRow struct {
	SourceID        string             `json:"source_id"`
	EntityID        string             `json:"entity_id"`
	Cause           pgtype.Text        `json:"cause"`
	Effect          pgtype.Text        `json:"effect"`
	HeaderText      string             `json:"header_text"`
	DescriptionText string             `json:"description_text"`
	Url             string             `json:"url"`
	ActiveFrom      pgtype.Timestamptz `json:"active_from"`
	ActiveUntil     pgtype.Timestamptz `json:"active_until"`
	FetchedAt       pgtype.Timestamptz `json:"fetched_at"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
}

func (q *Queries) GetCurrentAlert(ctx context.Context, arg GetCurrentAlertParams) (GetCurrentAlertRow, error) {
	row := q.db.QueryRow(ctx, getCurrentAlert, arg.SourceID, arg.EntityID)
	var i GetCurrentAlertRow
	err := row.Scan(
		&i.SourceID,
		&i.EntityID,
		&i.Cause,
		&i.Effect,
		&i.HeaderText,
		&i.DescriptionText,
		&i.Url,
		&i.ActiveFrom,
		&i.ActiveUntil,
		&i.FetchedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const hasReadyVehicleData = `-- name: HasReadyVehicleData :one
SELECT EXISTS (
  SELECT 1
  FROM realtime.vehicle_current vehicle
  JOIN realtime.snapshots snapshot ON snapshot.id = vehicle.snapshot_id
  JOIN ops.source_health health ON health.source_id = vehicle.source_id
  WHERE snapshot.is_valid
    AND health.last_valid_snapshot_at IS NOT NULL
)
`

// Readiness deliberately requires a valid snapshot and its corresponding
// successful source-health record. A database connection alone is not enough
// to describe stale or absent transit data as ready.
func (q *Queries) HasReadyVehicleData(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasReadyVehicleData)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listCurrentAlerts = `-- name: ListCurrentAlerts :many
SELECT source_id, entity_id, cause, effect, COALESCE(header_text,'') AS header_text,
       COALESCE(description_text,'') AS description_text, COALESCE(url,'') AS url,
       active_from, active_until, fetched_at, processed_at
FROM realtime.alerts_current
WHERE ($1::boolean = false OR (active_from IS NULL OR active_from <= $2) AND (active_until IS NULL OR active_until >= $2))
  AND ($3::text='' OR effect=$3)
  AND ($4::timestamptz IS NULL OR processed_at >= $4)
  AND (concat(source_id, ':alert:', entity_id) > $5::text)
ORDER BY processed_at DESC, source_id, entity_id
LIMIT $6
`

type ListCurrentAlertsParams struct {
	ActiveOnly   bool               `json:"active_only"`
	NowAt        pgtype.Timestamptz `json:"now_at"`
	Effect       string             `json:"effect"`
	UpdatedSince pgtype.Timestamptz `json:"updated_since"`
	Cursor       string             `json:"cursor"`
	RowLimit     int32              `json:"row_limit"`
}

type ListCurrentAlertsRow struct {
	SourceID        string             `json:"source_id"`
	EntityID        string             `json:"entity_id"`
	Cause           pgtype.Text        `json:"cause"`
	Effect          pgtype.Text        `json:"effect"`
	HeaderText      string             `json:"header_text"`
	DescriptionText string             `json:"description_text"`
	Url             string             `json:"url"`
	ActiveFrom      pgtype.Timestamptz `json:"active_from"`
	ActiveUntil     pgtype.Timestamptz `json:"active_until"`
	FetchedAt       pgtype.Timestamptz `json:"fetched_at"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
}

func (q *Queries) ListCurrentAlerts(ctx context.Context, arg ListCurrentAlertsParams) ([]ListCurrentAlertsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentAlerts,
		arg.ActiveOnly,
		arg.NowAt,
		arg.Effect,
		arg.UpdatedSince,
		arg.Cursor,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentAlertsRow{}
	for rows.Next() {
		var i ListCurrentAlertsRow
		if err := rows.Scan(
			&i.SourceID,
			&i.EntityID,
			&i.Cause,
			&i.Effect,
			&i.HeaderText,
			&i.DescriptionText,
			&i.Url,
			&i.ActiveFrom,
			&i.ActiveUntil,
			&i.FetchedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentVehicles = `-- name: ListCurrentVehicles :many
SELECT source_id, public_id, source_vehicle_id, route_public_id, trip_public_id, mode, direction_id,
       headsign, ST_X(point::geometry)::double precision AS longitude, ST_Y(point::geometry)::double precision AS latitude,
       bearing, speed_meters_per_second, in_service, source_updated_at, entity_updated_at,
       fetched_at, processed_at, freshness_status, snapshot_id
FROM realtime.vehicle_current
WHERE (cardinality($1::text[]) IS NULL OR source_id = ANY($1::text[]))
ORDER BY public_id
`

type ListCurrentVehiclesRow struct {
	SourceID             string                  `json:"source_id"`
	PublicID             string                  `json:"public_id"`
	SourceVehicleID      string                  `json:"source_vehicle_id"`
	RoutePublicID        pgtype.Text             `json:"route_public_id"`
	TripPublicID         pgtype.Text             `json:"trip_public_id"`
	Mode                 TransitMode             `json:"mode"`
	DirectionID          pgtype.Int2             `json:"direction_id"`
	Headsign             pgtype.Text             `json:"headsign"`
	Longitude            float64                 `json:"longitude"`
	Latitude             float64                 `json:"latitude"`
	Bearing              pgtype.Numeric          `json:"bearing"`
	SpeedMetersPerSecond pgtype.Numeric          `json:"speed_meters_per_second"`
	InService            bool                    `json:"in_service"`
	SourceUpdatedAt      pgtype.Timestamptz      `json:"source_updated_at"`
	EntityUpdatedAt      pgtype.Timestamptz      `json:"entity_updated_at"`
	FetchedAt            pgtype.Timestamptz      `json:"fetched_at"`
	ProcessedAt          pgtype.Timestamptz      `json:"processed_at"`
	FreshnessStatus      RealtimeFreshnessStatus `json:"freshness_status"`
	SnapshotID           int64                   `json:"snapshot_id"`
}

func (q *Queries) ListCurrentVehicles(ctx context.Context, sourceIds []string) ([]ListCurrentVehiclesRow, error) {
	rows, err := q.db.Query(ctx, listCurrentVehicles, sourceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentVehiclesRow{}
	for rows.Next() {
		var i ListCurrentVehiclesRow
		if err := rows.Scan(
			&i.SourceID,
			&i.PublicID,
			&i.SourceVehicleID,
			&i.RoutePublicID,
			&i.TripPublicID,
			&i.Mode,
			&i.DirectionID,
			&i.Headsign,
			&i.Longitude,
			&i.Latitude,
			&i.Bearing,
			&i.SpeedMetersPerSecond,
			&i.InService,
			&i.SourceUpdatedAt,
			&i.EntityUpdatedAt,
			&i.FetchedAt,
			&i.ProcessedAt,
			&i.FreshnessStatus,
			&i.SnapshotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStopArrivalCandidates = `-- name: ListStopArrivalCandidates :many
WITH active AS (
  SELECT id, version_label FROM catalog.feed_versions WHERE status='active'
), applicable AS (
  SELECT s.feed_version_id, s.service_id
  FROM transit.services s JOIN active f ON f.id=s.feed_version_id
  LEFT JOIN transit.service_calendar_dates d ON d.feed_version_id=s.feed_version_id AND d.service_id=s.service_id AND d.service_date=$4::date
  LEFT JOIN transit.service_calendars c ON c.feed_version_id=s.feed_version_id AND c.service_id=s.service_id
  WHERE COALESCE(d.exception_type=1, (c.start_date <= $4::date AND c.end_date >= $4::date AND CASE EXTRACT(ISODOW FROM $4::date) WHEN 1 THEN c.monday WHEN 2 THEN c.tuesday WHEN 3 THEN c.wednesday WHEN 4 THEN c.thursday WHEN 5 THEN c.friday WHEN 6 THEN c.saturday ELSE c.sunday END))
    AND COALESCE(d.exception_type, 0) <> 2
), updates AS (
 SELECT DISTINCT ON (tu.trip_public_id, su.stop_sequence) tu.trip_public_id, su.stop_sequence, tu.schedule_relationship AS trip_relationship,
   su.arrival_delay_seconds, su.arrival_time, su.departure_delay_seconds, su.departure_time, su.schedule_relationship AS stop_relationship,
   tu.source_id, tu.source_updated_at, tu.fetched_at, tu.processed_at
 FROM realtime.trip_updates_current tu
 JOIN realtime.trip_update_stop_times_current su ON su.source_id=tu.source_id AND su.entity_id=tu.entity_id
 ORDER BY tu.trip_public_id, su.stop_sequence, tu.processed_at DESC
)
SELECT t.public_id AS trip_id, t.route_public_id AS route_id, st.stop_public_id AS stop_id, st.stop_sequence, t.direction_id, COALESCE(t.headsign,'') AS headsign,
 COALESCE(st.departure_seconds, st.arrival_seconds) AS service_day_seconds, f.version_label,
 u.trip_relationship, u.stop_relationship, u.arrival_delay_seconds, u.arrival_time, u.departure_delay_seconds, u.departure_time,
 u.source_id AS realtime_source, u.source_updated_at, u.fetched_at AS realtime_fetched_at, u.processed_at AS realtime_processed_at
FROM transit.stop_times st
JOIN transit.trips t ON t.feed_version_id=st.feed_version_id AND t.public_id=st.trip_public_id
JOIN applicable a ON a.feed_version_id=t.feed_version_id AND a.service_id=t.service_id
JOIN active f ON f.id=t.feed_version_id
LEFT JOIN updates u ON u.trip_public_id=t.public_id AND u.stop_sequence=st.stop_sequence
WHERE st.stop_public_id=$1
 AND ($2::text='' OR t.route_public_id=$2)
 AND ($3::smallint IS NULL OR t.direction_id=$3::smallint)
ORDER BY COALESCE(st.departure_seconds, st.arrival_seconds), t.public_id, st.stop_sequence
`

type ListStopArrivalCandidatesParams struct {
	StopID      string      `json:"stop_id"`
	RouteID     string      `json:"route_id"`
	DirectionID pgtype.Int2 `json:"direction_id"`
	ServiceDate pgtype.Date `json:"service_date"`
}

type ListStopArrivalCandidatesRow struct {
	TripID                string             `json:"trip_id"`
	RouteID               string             `json:"route_id"`
	StopID                string             `json:"stop_id"`
	StopSequence          int32              `json:"stop_sequence"`
	DirectionID           pgtype.Int2        `json:"direction_id"`
	Headsign              string             `json:"headsign"`
	ServiceDaySeconds     pgtype.Int4        `json:"service_day_seconds"`
	VersionLabel          string             `json:"version_label"`
	TripRelationship      pgtype.Text        `json:"trip_relationship"`
	StopRelationship      pgtype.Text        `json:"stop_relationship"`
	ArrivalDelaySeconds   pgtype.Int4        `json:"arrival_delay_seconds"`
	ArrivalTime           pgtype.Timestamptz `json:"arrival_time"`
	DepartureDelaySeconds pgtype.Int4        `json:"departure_delay_seconds"`
	DepartureTime         pgtype.Timestamptz `json:"departure_time"`
	RealtimeSource        pgtype.Text        `json:"realtime_source"`
	SourceUpdatedAt       pgtype.Timestamptz `json:"source_updated_at"`
	RealtimeFetchedAt     pgtype.Timestamptz `json:"realtime_fetched_at"`
	RealtimeProcessedAt   pgtype.Timestamptz `json:"realtime_processed_at"`
}

// Current updates are optional enrichment. Static times are still returned
// when no matching valid realtime entity exists.
func (q *Queries) ListStopArrivalCandidates(ctx context.Context, arg ListStopArrivalCandidatesParams) ([]ListStopArrivalCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listStopArrivalCandidates,
		arg.StopID,
		arg.RouteID,
		arg.DirectionID,
		arg.ServiceDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStopArrivalCandidatesRow{}
	for rows.Next() {
		var i ListStopArrivalCandidatesRow
		if err := rows.Scan(
			&i.TripID,
			&i.RouteID,
			&i.StopID,
			&i.StopSequence,
			&i.DirectionID,
			&i.Headsign,
			&i.ServiceDaySeconds,
			&i.VersionLabel,
			&i.TripRelationship,
			&i.StopRelationship,
			&i.ArrivalDelaySeconds,
			&i.ArrivalTime,
			&i.DepartureDelaySeconds,
			&i.DepartureTime,
			&i.RealtimeSource,
			&i.SourceUpdatedAt,
			&i.RealtimeFetchedAt,
			&i.RealtimeProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStopSchedule = `-- name: ListStopSchedule :many
WITH active AS (
  SELECT id, version_label FROM catalog.feed_versions WHERE status = 'active'
), applicable AS (
  SELECT s.feed_version_id, s.service_id
  FROM transit.services s JOIN active f ON f.id = s.feed_version_id
  LEFT JOIN transit.service_calendar_dates d ON d.feed_version_id=s.feed_version_id AND d.service_id=s.service_id AND d.service_date=$6::date
  LEFT JOIN transit.service_calendars c ON c.feed_version_id=s.feed_version_id AND c.service_id=s.service_id
  WHERE COALESCE(d.exception_type=1, (c.start_date <= $6::date AND c.end_date >= $6::date AND CASE EXTRACT(ISODOW FROM $6::date) WHEN 1 THEN c.monday WHEN 2 THEN c.tuesday WHEN 3 THEN c.wednesday WHEN 4 THEN c.thursday WHEN 5 THEN c.friday WHEN 6 THEN c.saturday ELSE c.sunday END))
    AND COALESCE(d.exception_type, 0) <> 2
)
SELECT t.public_id AS trip_id, t.route_public_id AS route_id, st.stop_public_id AS stop_id, t.direction_id, COALESCE(t.headsign,'') AS headsign,
       COALESCE(st.departure_seconds, st.arrival_seconds) AS service_day_seconds, f.version_label
FROM transit.stop_times st
JOIN transit.trips t ON t.feed_version_id=st.feed_version_id AND t.public_id=st.trip_public_id
JOIN applicable a ON a.feed_version_id=t.feed_version_id AND a.service_id=t.service_id
JOIN active f ON f.id=t.feed_version_id
WHERE st.stop_public_id=$1
  AND ($2::text='' OR t.route_public_id=$2)
  AND ($3::smallint IS NULL OR t.direction_id=$3::smallint)
  AND ($4::text='' OR concat(t.public_id, ':', st.stop_sequence) > $4)
ORDER BY COALESCE(st.departure_seconds, st.arrival_seconds), t.public_id, st.stop_sequence
LIMIT $5
`

type ListStopScheduleParams struct {
	StopID      string      `json:"stop_id"`
	RouteID     string      `json:"route_id"`
	DirectionID pgtype.Int2 `json:"direction_id"`
	Cursor      string      `json:"cursor"`
	RowLimit    int32       `json:"row_limit"`
	ServiceDate pgtype.Date `json:"service_date"`
}

type ListStopScheduleRow struct {
	TripID            string      `json:"trip_id"`
	RouteID           string      `json:"route_id"`
	StopID            string      `json:"stop_id"`
	DirectionID       pgtype.Int2 `json:"direction_id"`
	Headsign          string      `json:"headsign"`
	ServiceDaySeconds pgtype.Int4 `json:"service_day_seconds"`
	VersionLabel      string      `json:"version_label"`
}

// Calendar exceptions take precedence over weekday service. Service-day seconds
// are deliberately returned unchanged so after-midnight trips remain correct.
func (q *Queries) ListStopSchedule(ctx context.Context, arg ListStopScheduleParams) ([]ListStopScheduleRow, error) {
	rows, err := q.db.Query(ctx, listStopSchedule,
		arg.StopID,
		arg.RouteID,
		arg.DirectionID,
		arg.Cursor,
		arg.RowLimit,
		arg.ServiceDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStopScheduleRow{}
	for rows.Next() {
		var i ListStopScheduleRow
		if err := rows.Scan(
			&i.TripID,
			&i.RouteID,
			&i.StopID,
			&i.DirectionID,
			&i.Headsign,
			&i.ServiceDaySeconds,
			&i.VersionLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicleHistory = `-- name: ListVehicleHistory :many
SELECT source_id, public_id, source_vehicle_id, route_public_id, trip_public_id,
       mode, ST_X(point::geometry)::double precision AS longitude,
       ST_Y(point::geometry)::double precision AS latitude, fetched_at,
       processed_at, freshness_status
FROM history.vehicle_observations
WHERE public_id=$1
  AND processed_at >= $2
  AND processed_at <= $3
  AND ($4::timestamptz IS NULL OR processed_at < $4::timestamptz)
ORDER BY processed_at DESC
LIMIT $5
`

type ListVehicleHistoryParams struct {
	PublicID string             `json:"public_id"`
	FromAt   pgtype.Timestamptz `json:"from_at"`
	ToAt     pgtype.Timestamptz `json:"to_at"`
	CursorAt pgtype.Timestamptz `json:"cursor_at"`
	RowLimit int32              `json:"row_limit"`
}

type ListVehicleHistoryRow struct {
	SourceID        string                  `json:"source_id"`
	PublicID        string                  `json:"public_id"`
	SourceVehicleID string                  `json:"source_vehicle_id"`
	RoutePublicID   pgtype.Text             `json:"route_public_id"`
	TripPublicID    pgtype.Text             `json:"trip_public_id"`
	Mode            TransitMode             `json:"mode"`
	Longitude       float64                 `json:"longitude"`
	Latitude        float64                 `json:"latitude"`
	FetchedAt       pgtype.Timestamptz      `json:"fetched_at"`
	ProcessedAt     pgtype.Timestamptz      `json:"processed_at"`
	FreshnessStatus RealtimeFreshnessStatus `json:"freshness_status"`
}

// Observations are normalized positions, not a claim about schedule adherence.
// A caller-enforced 30 day window keeps this read aligned with retention.
func (q *Queries) ListVehicleHistory(ctx context.Context, arg ListVehicleHistoryParams) ([]ListVehicleHistoryRow, error) {
	rows, err := q.db.Query(ctx, listVehicleHistory,
		arg.PublicID,
		arg.FromAt,
		arg.ToAt,
		arg.CursorAt,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVehicleHistoryRow{}
	for rows.Next() {
		var i ListVehicleHistoryRow
		if err := rows.Scan(
			&i.SourceID,
			&i.PublicID,
			&i.SourceVehicleID,
			&i.RoutePublicID,
			&i.TripPublicID,
			&i.Mode,
			&i.Longitude,
			&i.Latitude,
			&i.FetchedAt,
			&i.ProcessedAt,
			&i.FreshnessStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stopFeedTimezone = `-- name: StopFeedTimezone :one
SELECT f.service_timezone
FROM transit.stops s
JOIN catalog.feed_versions f ON f.id=s.feed_version_id
WHERE s.public_id=$1 AND f.status='active' AND f.service_timezone IS NOT NULL
LIMIT 1
`

func (q *Queries) StopFeedTimezone(ctx context.Context, stopID string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, stopFeedTimezone, stopID)
	var service_timezone pgtype.Text
	err := row.Scan(&service_timezone)
	return service_timezone, err
}
